"""Add EDIT transaction type

Revision ID: 251cd8f1299d
Revises: f5c04f4cd110
Create Date: 2026-02-10 16:36:04.611730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251cd8f1299d'
down_revision: Union[str, Sequence[str], None] = 'f5c04f4cd110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
