"""add_locations_table_and_transfer

Revision ID: 2a7de58569a0
Revises: e5f6g_remove_item_id_from_transactions
Create Date: 2026-02-23 16:38:47.605934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7de58569a0'
down_revision: Union[str, Sequence[str], None] = 'e5f6g_remove_item_id_from_transactions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_name'), ['name'], unique=True)

    # SQLite stores enums as VARCHAR — adding 'TRANSFER' requires no ALTER TABLE;
    # batch_alter_table handles it by recreating the table with the new enum values.

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_location_id'), ['location_id'], unique=False)
        batch_op.create_foreign_key('fk_items_location_id', 'locations', ['location_id'], ['id'])
        batch_op.drop_column('location')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('from_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_location_id', sa.Integer(), nullable=True))
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('ADD', 'REMOVE', 'EDIT', 'TRANSFER', name='transactiontype'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_transactions_location_id', 'locations', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_transactions_from_location_id', 'locations', ['from_location_id'], ['id'])
        batch_op.create_foreign_key('fk_transactions_to_location_id', 'locations', ['to_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_to_location_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_from_location_id', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_location_id', type_='foreignkey')
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('ADD', 'REMOVE', 'EDIT', 'TRANSFER', name='transactiontype'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('to_location_id')
        batch_op.drop_column('from_location_id')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_items_location_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_items_location_id'))
        batch_op.drop_column('location_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_name'))

    op.drop_table('locations')
    # ### end Alembic commands ###
